version: "3.7"

services:
  database_ignite:
    build: ./db
    container_name: database_ignite
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 3334:3334
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite
volumes:
  pgdata:
      driver: local